name: FlectoneChat
version: '${project.version}'
main: net.flectone.Main
api-version: 1.16
authors: [ TheFaser, fxd ]
softdepend: [ Vault, PlaceHolderAPI, voicechat, plasmovoice, InteractiveChat, LuckPerms, SuperVanish, DiscordSRV ]
commands:
  ignore:
    usage: /ignore <player>
    permission: flectonechat.ignore

  ignorelist:
    usage: /ignorelist
    permission: flectonechat.ignorelist

  msg:
    usage: /msg <player> <message>
    permission: flectonechat.msg

  try-cube:
    usage: /try-cube <number>
    permission: flectonechat.try-cube

  try:
    usage: /try <message>
    permission: flectonechat.try

  reply:
    usage: /r <message>
    permission: flectonechat.reply

  me:
    usage: /me <message>
    permission: flectonechat.me

  chatcolor:
    usage: /chatcolor <first color> <second color>
    permission: flectonechat.chatcolor

  spy:
    usage: /spy
    permission: flectonechat.spy

  flectonechat:
    usage: /flectonechat reload/config/locale
    permission: flectonechat.reload

  stream:
    usage: /stream start/end
    permission: flectonechat.stream

  ping:
    usage: /ping <player>
    permission: flectonechat.ping

  mark:
    usage: /mark
    permission: flectonechat.mark

  firstonline:
    usage: /firstonline <player>
    permission: flectonechat.firstonline

  lastonline:
    usage: /lastonline <player>
    permission: flectonechat.lastonline

  mail:
    usage: /mail <player> <message>
    permission: flectonechat.mail

  mail-clear:
    usage: /mail-clear <player> <number>
    permission: flectonechat.mail-clear

  afk:
    usage: /afk
    permission: flectonechat.afk

  mute:
    usage: /mute <player> <time> <reason>
    permission: flectonechat.mute

  unmute:
    usage: /unmute <player>
    permission: flectonechat.mute

  helper:
    usage: /helper <message>
    permission: flectonechat.helper

  maintenance:
    usage: /maintenance on/off
    permission: flectonechat.maintenance

  switch-chat:
    usage: /switch-chat switch/hide local/global
    permission: flectonechat.switch-chat

  ball:
    usage: /ball <message>
    permission: flectonechat.ball

  tic-tac-toe:
    usage: /tic-tac-toe <player>
    permission: flectonechat.tic-tac-toe

  clear-chat:
    usage: /clearchat
    permission: flectonechat.clear-chat

  tempban:
    usage: /tempban <player> <time> <reason>
    permission: flectonechat.ban

  unban:
    usage: /unban <player>
    permission: flectonechat.ban

  warn:
    usage: /warn <player> <time> <reason>
    permission: flectonechat.warn

  warnlist:
    usage: /warnlist <player>
    permission: flectonechat.warnlist

  unwarn:
    usage: /unwarn <player> <index>
    permission: flectonechat.warn

  banlist:
    usage: /banlist
    permission: flectonechat.banlist

  mutelist:
    usage: /mutelist
    permission: flectonechat.mutelist

  broadcast:
    usage: /broadcast <message>
    permission: flectonechat.broadcast

  poll:
    usage: /poll create/vote
    permission: flectonechat.pollvote

  chat-settings:
    usage: /chat-settings
    permission: flectonechat.chat-settings

  kick:
    usage: /kick <player> <message>
    permission: flectonechat.kick

  spit:
    usage: /spit
    permission: flectonechat.spit

permissions:
  flectonechat.reload:
    default: op
  flectonechat.ignore:
    default: true
  flectonechat.ignorelist:
    default: true
  flectonechat.msg:
    default: true
  flectonechat.try:
    default: true
  flectonechat.try-cube:
    default: true
  flectonechat.reply:
    default: true
  flectonechat.me:
    default: true
  flectonechat.chatcolor:
    default: true
  flectonechat.stream:
    default: false
  flectonechat.ping:
    default: true
  flectonechat.mark:
    default: true
  flectonechat.firstonline:
    default: true
  flectonechat.lastonline:
    default: true
  flectonechat.mail:
    default: true
  flectonechat.mail-clear:
    default: true
  flectonechat.afk:
    default: true
  flectonechat.mute:
    default: op
  flectonechat.helper:
    default: true
  flectonechat.maintenance:
    default: op
  flectonechat.switch-chat:
    default: true
  flectonechat.ball:
    default: true
  flectonechat.tic-tac-toe:
    default: true
  flectonechat.clear-chat:
    default: true
  flectonechat.ban:
    default: op
  flectonechat.broadcast:
    default: op
  flectonechat.pollvote:
    default: true
  flectonechat.banlist:
    default: op
  flectonechat.mutelist:
    default: op
  flectonechat.chat-settings:
    default: true
  flectonechat.spy:
    default: op
  flectonechat.warn:
    default: op
  flectonechat.warnlist:
    default: op
  flectonechat.chat.cords:
    default: true
  flectonechat.chat.stats:
    default: true
  flectonechat.chat.ping:
    default: true
  flectonechat.chat.url:
    default: true
  flectonechat.chat.tooltip:
    default: true
  flectonechat.chat.markdown-||:
    default: true
  flectonechat.chat.markdown-**:
    default: true
  flectonechat.chat.markdown-__:
    default: true
  flectonechat.chat.markdown-##:
    default: true
  flectonechat.chat.markdown-??:
    default: true
  flectonechat.chat.markdown-~~:
    default: true
  flectonechat.chat.anvil-formatting:
    default: true
  flectonechat.chat.book-formatting:
    default: true
  flectonechat.chat.sign-formatting:
    default: true
  flectonechat.kick:
    default: op
  flectonechat.chat-settings.advancement:
    default: true
  flectonechat.chat-settings.death:
    default: true
  flectonechat.chat-settings.join:
    default: true
  flectonechat.chat-settings.quit:
    default: true
  flectonechat.chat-settings.me:
    default: true
  flectonechat.chat-settings.try:
    default: true
  flectonechat.chat-settings.try-cube:
    default: true
  flectonechat.chat-settings.ball:
    default: true
  flectonechat.chat-settings.tempban:
    default: true
  flectonechat.chat-settings.mute:
    default: true
  flectonechat.chat-settings.warn:
    default: true
  flectonechat.chat-settings.msg:
    default: true
  flectonechat.chat-settings.reply:
    default: true
  flectonechat.chat-settings.mail:
    default: true
  flectonechat.chat-settings.tic-tac-toe:
    default: true
  flectonechat.chat-settings.kick:
    default: true
  flectonechat.chat-settings.auto-message:
    default: true
  flectonechat.spit:
    default: true